### ISSUE TITLE
I am getting error with tifffile library.

### ISSUE THREAD

**Issue by khoroshyy** [jacopoabramo/napari-live-recording#22]
Hi.
When I try to start plugin I am getting this error:
ailed to import command at 'napari_live_recording:NapariLiveRecording': cannot import name 'PHOTOMETRIC' from 'tifffile.tifffile' (/home/petro/miniconda3/envs/pyfluoval/lib/python3.9/site-packages/tifffile/tifffile.py)
Any idea what is the problem?

**Comment by jacopoabramo** [comment]
hey @khoroshyy, thanks for trying my plugin.

I'm thinking the error is caused by the fact that you're using an older version of the tifffile package. Could you try installing the latest release of it?

**Comment by khoroshyy** [comment]
@jacopoabramo tifffile update does not help. :(

**Comment by jacopoabramo** [comment]
What OS do you have and which python version are you running?

**Comment by jacopoabramo** [comment]
Try updating to the newest release

**Comment by jacopoabramo** [comment]
hey @khoroshyy, did you manage to solve the issue?

**Comment by khoroshyy** [comment]
Sorry, I had no time for it yet :(

**Comment by khoroshyy** [comment]
After reinstalling it I do not have this error anymore. I got some other ones. But I will make another issue for it.
