### ISSUE TITLE
pymmcore-plus: remove startup debug information

### ISSUE THREAD

**Issue by jacopoabramo** [jacopoabramo/napari-live-recording#26]
At startup of the plugin whenever it tries to discover all possible device adapters available in the Micro-Manager core, it shows the following:

```
Discovering HID Devices......
HID Device pid: 608d vid: 608d
HID Device pid: 6099 vid: 6099
HID Device pid: 6099 vid: 6099
HID Device pid: 6099 vid: 6099
Discovering USB Devices......
```

Can this be removed somehow?

**Comment by jacopoabramo** [comment]
@felixwanitschke do you have updates on this?

**Comment by felixwanitschke** [comment]
I tried what was suggested to me in this Issue [https://github.com/pymmcore-plus/pymmcore-plus/issues/286](url), but it did not work out. Maybe I did smth. wrong or misunderstood it, so it might be worthy that you also have a try.

**Comment by jacopoabramo** [comment]
I'll close the issue because as mentioned in [here](https://github.com/pymmcore-plus/pymmcore-plus/issues/286) this is hard coded into one of the device adapters. We'll just have to live with it for now.
