### ISSUE TITLE
Select camera for opencvgraber?

### ISSUE THREAD

**Issue by khoroshyy** [jacopoabramo/napari-live-recording#29]
Hi. Is it possible to select camera when using opencvgrabber?
Thanks.
Petro.

**Comment by jacopoabramo** [comment]
Hi @khoroshyy , yes it is possible:

![image](https://github.com/jacopoabramo/napari-live-recording/assets/20145526/2a5f0356-f008-41ed-915a-d966ac449a0e)

You can change the Camera ID/SN field to add a secondary OpenCV grabber. Usually it should be sequential numbers: first camera -> ID 0, second camera -> ID 1, ...

If that helps you please close the issue.

**Comment by jacopoabramo** [comment]
Interesting. Please send me the following information:

- python version
- napari version
- which operating system you're currently using

If it's on Windows/Linux I can try to recreate this, if it's on a Mac I may have some difficulties because I don't have one

**Comment by khoroshyy** [comment]
Hi, I use the 0.3.3 version, 
Napari installed via anaconda no Win11.
Attached is  a yml file of the environment.
[a.zip](https://github.com/jacopoabramo/napari-live-recording/files/14591462/a.zip)

**Comment by jacopoabramo** [comment]
@khoroshyy I verified the behavior and can confirm it's a bug.

I made a small fix unrelated to the issue and tested again in a fresh environment with only napari and the plugin installed. Could you please check with version 0.3.4 if the bug still occurs?

**Comment by khoroshyy** [comment]
![image](https://github.com/jacopoabramo/napari-live-recording/assets/1734704/43ac5c48-5f34-46ef-87fa-798160c2f092)

Now it is OK

**Comment by jacopoabramo** [comment]
Great! Is it okay to close the issue then?

**Comment by khoroshyy** [comment]
Yes, go ahead.
